[project]
name = "ds-mcp"
version = "0.1.0"
description = "MCP server for data science projects"
authors = []
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[tasks]
serve = "python -m ds_mcp.server"
test = "pytest"
lint = "pre-commit run --all-files"

[dependencies]
python = ">=3.10"
fastapi = ">=0.104.0"
uvicorn = ">=0.23.2"
pydantic = ">=2.4.2"
pydantic-settings = ">=2.0.0"
python-dotenv = ">=1.0.0"
loguru = ">=0.7.2"
pytest = ">=7.4.2"
ruff = ">=0.0.292"
pre-commit = ">=3.5.0"
